version: '3'
services:
  nginix:
    image: nginx
    restart: always
    ports:
     - "81:80"
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres
    restart: always
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=25ePM%B4Q=mu
      - POSTGRES_DB=blog
    ports:
      - "5433:5432"
  backend:
    build: .
    restart: always
    command: bash -c "cd /app && npx sequelize-cli db:migrate && npm start"
    #command: bash -c "tail -f /dev/null"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
      - elasticsearch
    volumes:
      - ./:/app
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300 
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    #command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache:/data
